[package]
name = "grpc-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "helloworld-server"
path = "src/server.rs"

[dependencies]
tonic = "0.6.1"
prost = "0.9.0"
tokio = {version = "1.13.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.6.0"
